package com.ex.simplecrudrest.dao.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA Entity representation of a Pet for relational database persistence.
 * This class is specific to JPA/relational database implementation and should only be used
 * within the JpaPetDao implementation. The domain layer uses the pure Pet domain model.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "pets")
public class PetJpaEntity {

    /**
     * Unique identifier for the pet (auto-generated by database)
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * Name of the pet (required)
     */
    @Column(name = "name", nullable = false, length = 100)
    private String name;

    /**
     * Species of the pet (e.g., "Dog", "Cat", "Rabbit") (required)
     */
    @Column(name = "species", nullable = false, length = 50)
    private String species;

    /**
     * Age of the pet in years (optional, must be >= 0 if provided)
     */
    @Column(name = "age")
    private Integer age;

    /**
     * Name of the pet's owner (optional)
     */
    @Column(name = "owner_name", length = 100)
    private String ownerName;
}
